user www-data;

events{
}

http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;
    error_log /dev/stderr;

    server{
        listen 443 ssl;
        server_name aben-hzz.42.fr;

        location / {
            return 200 "Raiklings here!\n";
        }

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
    }
}